### ISSUE TITLE
Adding support for multiple domains

### ISSUE THREAD

**Issue by danielsiwiec** [git-duet/git-duet#44]
It would be great to allow emails from multiple domains. Maybe something like this would work:

```
authors:
  jd: Jane Doe; jane
  fb: Frances Bar
  js: john.smith@overtherainbow.com
email:
  domain: awesometown.local
```

So, if the author has the email provided, use that instead.

**Comment by jszwedko** [comment]
Hey @danielsiwiec,

It's kind of buried towards the bottom of the README, but this is actually possible via something like:

```
pairs:
  jd: Jane Doe
  fb: Frances Bar
email:
  domain: awesometown.local
email_addresses:
  jd: jane@awesome.local
```

Where it'll use the given address for Jane and build the one for Frances.
