### ISSUE TITLE
duet-pre-commit + git solo not working

### ISSUE THREAD

**Issue by bguedel** [git-duet/git-duet#68]
### Configuration
```sh
export GIT_DUET_GLOBAL=true
export GIT_DUET_CO_AUTHORED_BY=true
export GIT_DUET_SECONDS_AGO_STALE=36000 # 10 hours
git duet-install-hook pre-commit # run this command in a git repository. https://github.com/git-duet/git-duet/issues/61
```

### .git-authors
```yml
authors:
  me: MMM EEE
  hm: HHH MMM
  hr: HHH RRR
  tm: TTT MMM
email_template: '{{with replace .Name " " "" -1}}{{toLower .}}{{end}}@domain.com' # firstlast@domain.com
```
### hooks
pre-commit
```sh
#!/usr/bin/env bash
exec git duet-pre-commit "$@"
```
prepare-commit-msg
```sh
#!/usr/bin/env bash
exec git duet-prepare-commit-msg "$@"
```

When doing a git solo
1) it doesnt remove the previous duet
2) if it doesnt have the previous duet, it doesnt update the stale seconds -- and refuses to let me commit.
